### ISSUE TITLE
Not readable text

### ISSUE THREAD

**Issue by AxelThePop** [antfu/vscode-where-am-i#1]
The text is not readable(on the left, almost invisible)

![Annotation 2020-05-23 225450](https://user-images.githubusercontent.com/52045202/82739481-8a329b80-9d48-11ea-82ec-f3c8a55fceda.jpg)

**Comment by antfu** [comment]
The color is generated from the workspace full path(seeded random). I would add a custom color configure later.

**Comment by antfu** [comment]
in v0.1.2 you can either:

Disable color
```jsonc
"where-am-i.colorful": false
```
or run the command `Where Am I: Config the name and color` to change the name and color

**Comment by octref** [comment]
It's possible to read VS Code's status bar color with `vscode.ThemeColor`. I suggest regenerating colors until color satisfies a certain contrast ratio.

**Comment by antfu** [comment]
Thanks for the tips and we could definitely use it 

However, I am not sure about having color text on top of colored background even they have a good enough contrast ratio. (for example orange text + blue background).

One way is that we can check `vscode.ThemeColor` to determine whether we should enable the `colorful` mode automatically. Or I would suggest overriding the status bar color closer to the editor background by

```json
  "workbench.colorCustomizations": {
    "statusBar.background": "#222"
  },
```

And more ideally, I would hope we could have something like the "Remote Host" to have its own background. Sad for VS Code does not offer a public API for this. 😢

![image](https://user-images.githubusercontent.com/11247099/95163244-08647b80-07da-11eb-881d-e19859b6bbea.png)

**Comment by octref** [comment]
> having color text on top of colored background even they have a good enough contrast ratio. (for example orange text + blue background).

I'd say
- regenrate fg color until satisfying contrast ratio
- offer a command to regenerate icon + color until user is happy :p
