### ISSUE TITLE
大佬，mac上打开选择项目窗口的快捷键是什么呢，如何配置

### ISSUE THREAD

**Issue by yzh990918** [antfu/vscode-where-am-i#14]

**Comment by antfu** [comment]
Ctrl+R, Google yourself next time.

**Comment by yzh990918** [comment]
> Ctrl+R, Google yourself next time.
感谢大佬回复，不过我是想问呼起这个插件的面板的快捷键,也就是这个窗口
<img width="661" alt="image" src="https://user-images.githubusercontent.com/46418596/174518391-f19e7af3-7950-4925-b523-c42f831246c0.png">

**Comment by kortin99** [comment]
Ctrl+W, Google yourself next time.🤦‍♂️
