### ISSUE TITLE
Screenshot and why

### ISSUE THREAD

**Issue by linonetwo** [antfu/vscode-where-am-i#19]
### Clear and concise description of the problem

Why need this, top already have name

<img width="383" alt="截屏2023-08-16 12 19 13" src="https://github.com/antfu/vscode-where-am-i/assets/3746270/f748179a-29e8-4dd9-bd55-fb4ee129b41f">

### Suggested solution

Don't know why

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Then congrats you don't need this :)
