### ISSUE TITLE
Don't modify capitalization

### ISSUE THREAD

**Issue by dsernst** [antfu/vscode-where-am-i#8]
This is very cool.

But surprised that it's modifying folder capitalization:

### `VipassanaGong` became `Vipassanagong`
<img width="711" alt="image" src="https://user-images.githubusercontent.com/6340841/157837845-a80fdbc0-337a-4ab9-ac91-28ee1ff67b2b.png">

Would expect it to match the displayed name in the titlebar.

**Comment by dsernst** [comment]
Oh, now I see there is a `textTransform` setting, neat

https://github.com/antfu/vscode-where-am-i/blob/47e0a3e9c6b005f370f175593486c9d6ae7959ac/src/extension.ts#L16

Looking into how to disable... 🕵️

**Comment by dsernst** [comment]
Found it.

Workspace settings (`Cmd+p > 'Preferences: Open Workspace Settings'`), Where-am-i: Text Transform

<img width="573" alt="image" src="https://user-images.githubusercontent.com/6340841/157839744-576c0c48-02ff-4b17-9a2b-7d456f949486.png">

Or add to `./.vscode/settings.json` file:

```json
"where-am-i.textTransfrom": "none"
```

**Comment by dsernst** [comment]
Looks like a typo there?

```diff
-textTransfrom
+textTransform
```

**Comment by dsernst** [comment]
I also found it useful to reset my user setting for: `"where-am-i.textTransfrom": "none"`

I'm personally satisfied, so I'll close this issue. 

Maybe it will be helpful to someone else one day.

Thx again for the great extension. 😄

**Comment by antfu** [comment]
PR welcome to the typo. Thanks :)

**Comment by dsernst** [comment]
K, will break people's previous setting though, afaik. Unless VS Code has a fancy way to migrate settings?
